Kir Kanos (V)
swccgpc/holotable pull request #99
Opened 2021-02-26 18:40 UTC by ronhowe

Updated errata'd gametext consistent with PDF.

2021-02-26 22:57 UTC, jriendeau requested changes
The text on Scomp says "During battle, if with an Imperial and present at a site, once ..."

2021-02-26 23:19 UTC, ronhowe commented
Fixed.

2021-02-27 01:01 UTC, jriendeau approved these changes

2021-02-27 01:01 UTC, jriendeau commented
Thanks for fixing it!

2021-02-27 01:01 UTC, merged